version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: "increase-if-necessary"
    ignore:
      - dependency-name: "copy-text-to-clipboard"
        versions:
          - ">= 3.0.0"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    groups:
      actions-minor-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
      actions-major:
        patterns:
          - '*'
        update-types:
          - major
    cooldown:
      default-days: 7
      semver-major-days: 14
